clear;
format long;

n = 3;
m = 2;
q = 0.1;
r = 0.1;
N = 20;

randn('state', 0);

f = @(x)[x(2); x(3); 0.05 * x(1) * (x(2) + x(3))];
h = @(x)x(1:m);

s = [0; 0; 1];
x0 = s + q * randn(n, 1);

rows = zeros(N, n + m);
for k = 1:N
  z = h(s) + r * randn(m, 1);
  rows(k, :) = [s' z'];
  s = f(s) + q * randn(n, 1);
end

fid = fopen('ukf_input.txt', 'w');
if fid < 0
  error('failed to open ukf_input.txt for writing');
end

fprintf(fid, '# ukf_input.txt\n');
fprintf(fid, '# Generated by gen_ukf_input_txt.m (Octave/Matlab)\n');
fprintf(fid, '# Model (from ukf_main.m):\n');
fprintf(fid, '#   x_{k+1} = f(x_k) + w_k,  w ~ N(0, Q)\n');
fprintf(fid, '#   z_k     = h(x_k) + v_k,  v ~ N(0, R)\n');
fprintf(fid, '# Dimensions:\n');
fprintf(fid, '#   n (state dim) = %d\n', n);
fprintf(fid, '#   m (meas dim)  = %d\n', m);
fprintf(fid, '# Noise std (from ukf_main.m):\n');
fprintf(fid, '#   q = %.17g, r = %.17g\n', q, r);
fprintf(fid, '# Square-root noise covariance (used by ukf.m UT):\n');
fprintf(fid, '#   Qs = q * I_n\n');
fprintf(fid, '#   Rs = r * I_m\n');
fprintf(fid, '# UKF steps:\n');
fprintf(fid, 'N %d\n', N);
fprintf(fid, '# Initial filter estimate x0 (used as ukf.m input x before step 1):\n');
fprintf(fid, '# columns: x0_1 x0_2 x0_3\n');
fprintf(fid, 'x0 %.17g %.17g %.17g\n', x0(1), x0(2), x0(3));
fprintf(fid, '# Per-step ground-truth state and measurement (for k=1..N):\n');
fprintf(fid, '# columns: k s1 s2 s3 z1 z2\n');
for k = 1:N
  fprintf(fid, '%d %.17g %.17g %.17g %.17g %.17g\n', k, rows(k, 1), rows(k, 2), rows(k, 3), rows(k, 4), rows(k, 5));
end
fclose(fid);
