% Reference: R. van der Merwe and E. Wan. 
% The Square-Root Unscented Kalman Filter for State and Parameter-Estimation, 2001
%
% By Zhe Hu at City University of Hong Kong, 05/01/2017
n=3;      %dimension of state
m=2;      %dimension of measurement
q=0.1;    %std of process 
r=0.1;    %std of measurement
Qs=q*eye(n); % std matrix of process
Rs=r*eye(m);        % std of measurement  
f=@(x)[x(2);x(3);0.05*x(1)*(x(2)+x(3))];  % nonlinear state equations
h=@(x)x(1:m);                               % measurement equation
fid_in = fopen('ukf_input.txt', 'r');
if fid_in < 0
  error('failed to open ukf_input.txt');
end
N = [];
x = [];
rows = [];
while true
  line = fgetl(fid_in);
  if ~ischar(line)
    break;
  end
  line = strtrim(line);
  if isempty(line) || line(1) == '#'
    continue;
  end

  if length(line) >= 2 && strcmp(line(1:2), 'N ')
    vals = sscanf(line, 'N %d');
    if numel(vals) ~= 1
      error('invalid N line in ukf_input.txt');
    end
    N = vals(1);
    continue;
  end

  if length(line) >= 3 && strcmp(line(1:3), 'x0 ')
    vals = sscanf(line, 'x0 %f %f %f');
    if numel(vals) ~= n
      error('invalid x0 line in ukf_input.txt');
    end
    x = vals(:);
    continue;
  end

  vals = sscanf(line, '%f');
  if numel(vals) ~= (1 + n + m)
    error('invalid data row in ukf_input.txt: expected %d numbers, got %d', 1+n+m, numel(vals));
  end
  rows(end+1, :) = vals(:)'; %#ok<AGROW>
end
fclose(fid_in);

if isempty(N) || isempty(x)
  error('missing N or x0 in ukf_input.txt');
end
if size(rows, 1) ~= N
  error('ukf_input.txt size mismatch: expected %d data rows, got %d', N, size(rows,1));
end
sV = rows(:, 2:1+n)';
zV = rows(:, 2+n:1+n+m)';
S = eye(n);                               % initial square root of state covraiance
xV = zeros(n,N);          %estmate        % allocate memory
SV = zeros(n,n,N);
for k=1:N
  z = zV(:,k);
  [x, S] = ukf(f,x,S,h,z,Qs,Rs);            % ukf 
  xV(:,k) = x;                            % save estimate
  SV(:,:,k) = S;
end
fid = fopen('ukf_output.txt', 'w');
if fid < 0
  error('failed to open ukf_output.txt for writing');
end
fprintf(fid, '# ukf_output.txt\n');
fprintf(fid, '# Generated by ukf_main.m (Octave/Matlab)\n');
fprintf(fid, '# Input file: ukf_input.txt\n');
fprintf(fid, '# Dimensions: n=%d, m=%d\n', n, m);
fprintf(fid, '# Noise std: q=%.17g, r=%.17g\n', q, r);
fprintf(fid, 'N %d\n', N);
fprintf(fid, '# rows: k z1 z2 x1 x2 x3 S11 S12 S13 S22 S23 S33\n');
for k = 1:N
  Sk = SV(:,:,k);
  fprintf(fid, '%d %.17g %.17g %.17g %.17g %.17g %.17g %.17g %.17g %.17g %.17g %.17g\n', ...
    k, zV(1,k), zV(2,k), xV(1,k), xV(2,k), xV(3,k), Sk(1,1), Sk(1,2), Sk(1,3), Sk(2,2), Sk(2,3), Sk(3,3));
end
fclose(fid);

graphics_toolkit('gnuplot');
figure('visible', 'off');
for k=1:n
  subplot(n,1,k);
  plot(1:N, sV(k,:), '-', 1:N, xV(k,:), '--');
end
print('ukf_state_compare.png', '-dpng');
close all;
